." Hi! This manual (man page) was written by dd86k.
." Please read man-pages(7) and groff_man(7) about the manual page format.
." Don't forget to respect the format of this document!
."
.TH ddcpuid 1 "October 2022" dd86k "User manual"
.SH NAME
ddcpuid - x86/AMD64 CPUID information tool

.SH SYNOPSIS
.SY ddcpuid
.OP \-a
.OP \-r [LEVEL[,SUBLEVEL]]
.OP \-o
.OP \-b
.OP \--list
.OP \--baseline
.OP \--raw [LEVEL[,SUBLEVEL]]
.OP \--ver
.OP \--version
.OP \--help
.YS

.SH DESCRIPTION
.B ddcpuid
is a simple x86/AMD64 CPUID information tool.

Processor technologies are reported per processor vendor, depending if
available in documentation. Only Intel and AMD processors are supported.
Some paravirtualization interfaces are supported (notably Hyper-V, KVM,
and the VBox Minimal interfaces).

By default, the following is reported:

.EX
- Vendor and Brand strings;
- Identification numbers;
- Core/thread information;
- Maximum amount of memory supported;
- Baseline;
- Technologies;
- Legacy and generic extensions;
- SSE extensions;
- AVX extensions;
- AMX extensions;
- Security mitigations;
- Paravirtualization interface, if detected;
- And cache topology.
.EE

." TODO: Sort options alphabetically

.SH OPTIONS
.IP -h, --help
Show help screen and exit.

.IP --version
Show version screen and exit.

.IP --ver
Show version only and exit.

.IP -l,\ \-\-list
Print all available processor information.

This is best suited for software developers.

.IP -o
Overrides leaves to 0x40h, 0x4000_0040, and 0x8000_0040. Affects feature
scanning and -r/--raw.

.IP -r,\ \-\-raw
Print a raw table of CPUID data. The table is Markdown-compatible.

Also accepts optional leaf/subleaf inputs.

Note: Default, the sub-leaf input (ECX) is cleared.

.IP -b,\ \-\-baseline

Show which baseline the processor fits in.

No error codes are set.

.SH EXAMPLES

.IP ddcpuid

Shows a summary of processor specifications.

.IP ddcpuid\ \-\-list

Shows a detailed list of processor details.

.IP ddcpuid\ \-\-raw\ 4,1

Shows a raw CPUID table given input leaf 0x4 and input subleaf 0x1.

.SH NOTES
This man-page was written for ddcpuid 0.21. The full technical manual contains
more details, such as explanations to intel and amd technologies, as well as
various extensions in detail.

.UR https://dd86k.space/docs/ddcpuid-manual.pdf
Manual:
.UE
(PDF)

While the best supported compiler is DMD, LDC offers superior optimizations.

.SH BUGS
May misreport due to human error.

.SH AUTHOR
Written by dd86k.

.SH CONTACT
.UR https://git.dd86k.space/dd86k/ddcpuid
Homepage:
.UE

.UR https://github.com/dd86k/ddcpuid
Mirror:
.UE

.MT dd@dax.moe
Email:
.ME

.SH HISTORY
This project started February 26, 2016 out of curiosity.