." Hi! This manual (man page) was written by dd86k.
." Please read man-pages(7) and groff_man(7) about the manual page format.
." Don't forget to respect the format of this document!
."
.TH ddcpuid 1 "November 2019" dd86k "User manual"
.SH NAME
ddcpuid - Simple x86/AMD64 CPUID tool

.SH SYNOPSIS
.SY ddcpuid
.OP \-r
.OP \-o
.OP \-s [...]
.OP \--help
.OP \--version
.YS

.SH DESCRIPTION
.B ddcpuid
is a simple x86/AMD64 CPUID information tool.

Processor technologies are reported per processor vendor, depending if
available in documentation. Only Intel and AMD processors are supported.

The following is reported:

.EX
- Vendor and Brand strings
- Identification numbers
- x86 extensions (e.g. MMX, AVX, etc.)
- Stand-alone instructions (e.g. RDRAND)
- Cache information
- ACPI features
- Virtualization features
- Memory features
- Debugging features
- Security features
- Miscellaneous details
  - CPUID Leaves
  - Type
  - Index
  - xTPR
  - PBE
  - LAHF64+SAHF64
.EE

.SH OPTIONS
.IP -h, --help
Show help screen and exit.

.IP --version
Show version screen and exit.

.IP -r
Print a raw table of CPUID data.

Note: ECX is always cleared.

.IP -o
Overrides max leaf to 20h and extended max leaf to 8000_0020h. Affects feature
scanning and -r.

.IP -s
For -r only: provide maximum sub-leaf.

.SH WARNINGS
ddcpuid is still currently going under active development, you may encounter
bugs or incorrect reporting.

.SH NOTES
A full user manual is available
.UR https://dd86k.space/docs/ddcpuid-manual.pdf
online
.UE
(PDF).

Best supported compiler is DMD.

.SH BUGS
Compiling with GDC/GCC, compiling above -O1 segfaults at run-time.

.SH AUTHOR
Written by dd86k.

.SH CONTACT
.UR https://git.dd86k.space/dd86k/ddcpuid
Homepage:
.UE

.MT dd@dax.moe
Email:
.ME

.SH HISTORY
This project started February 26, 2016.