." Hi! This manual (man page) was written by dd86k.
." Please read man-pages(7) and groff_man(7) about the manual page format.
." Don't forget to respect the format of this document!
."
.TH ddcpuid 1 "November 2018" dd86k "User manual"
.SH NAME
ddcpuid - Simple x86/AMD64 CPUID tool

.SH SYNOPSIS
.SY ddcpuid
.OP \-rodfvh
.YS

.SH DESCRIPTION
.B ddcpuid
is a simple x86/AMD64 CPUID tool, getting the most out in a Ring 3 context (CPL=3). It reports on quite a few bits, such as processor vendor, processor brand string, cache, processor extentions, and processor technologies.

.SH OPTIONS
.IP -h
Show help screen and exit.

.IP -v
Show version screen and exit.

.IP -r
Print a raw table of CPUID data.

Note: ECX is always cleared.

.IP -o
Overrides max leaf to 20h and extended max leaf to 8000_0020h. Affects feature scanning and -r.

.IP -d
Advanced mode, where ddcpuid prints a lot more detailed information.

.EX
Includes:
- Detailed cache information
- Max leaves
- FPU features
- ACPI features
- Virtualization features
- Memory features
- Debugging features
- Security features
- Miscellaneous details
.EE

.IP -f
Show future extensions, such as features not yet present in the reference manuals.

.SH WARNINGS
ddcpuid is still currently going under active development, you may encounter bugs or incorrect reporting.

.SH NOTES
Processor technologies are reported per processor vendor, depending if available in documentation.

.SH BUGS
None at the moment.

.SH AUTHOR
Written by dd86k.

.SH CONTACT
.UR https://github.com/dd86k/ddcpuid
Homepage:
.UE

.MT devddstuff@gmail.com
Email:
.ME

.SH HISTORY
This project started in February 26, 2016.