name: D-dmd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
    - name: 'Build'
      run: dub build --compiler=dmd
    - name: 'Test'
      run: dub test --compiler=dmd